### ISSUE TITLE
Use remote paths (URLs) for projects and observed data in quali plan

### ISSUE THREAD

**Issue by Yuri05** [sfrechen/Qualification-DDI-CYP3A4#1]
Remove submodules, when done

**Comment by sfrechen** [comment]
Done.

**Comment by Yuri05** [comment]
almost done: paths are buggy
"Path": "https://raw.githubusercontent.com/sfrechen/idazolam-Model/master/Midazolam-Model.json"

**Comment by Yuri05** [comment]
and still some local paths, hmm
"Path": "../../Itraconazole/Itraconazole-Model.json",
