### ISSUE TITLE
Wrong output paths

### ISSUE THREAD

**Issue by Yuri05** [sfrechen/Qualification-DDI-CYP3A4#2]
E.g. "PeripheralVenousBlood|Plasma|Midazolam" is wrong
In order to see the proper path: select output(s) of interest in any simulation in PK-Sim and export project to snapshot, then check `OutputSelections `under simulation.

Below you see e.g. how the output for "PeripheralVenousBlood|Plasma|C1" must be entered in JSON

![grafik](https://user-images.githubusercontent.com/25061876/56842751-3fbac300-6899-11e9-9a0f-f05b6e760ec0.png)

**Comment by sfrechen** [comment]
corrected
