### ISSUE TITLE
Invalid snapshot configuration part 2

### ISSUE THREAD

**Issue by Yuri05** [sfrechen/Qualification-DDI-CYP3A4#5]
_Error: Could not find Simulation '**DDI Control - Ahonen 1995**' in snapshot 'Itraconazole-Midazolam-DDI'._
_Error: Could not find Simulation '**DDI Control - Backman 1998**' in snapshot 'Itraconazole-Midazolam-DDI'._
and so on

**Comment by sfrechen** [comment]
fixed
