### ISSUE TITLE
wrong simulation name?

### ISSUE THREAD

**Issue by Yuri05** [sfrechen/Qualification-DDI-CYP3A4#7]
"Simulation": "po 100 mg QD (Templeton 08) sol fast" seems not to exist in project Itraconazole
* https://github.com/sfrechen/Qualification-DDI-CYP3A4/blob/7641759048775649e0de7ede9f554184a80c0029/input/master_quali_plan.json#L2859
* https://github.com/sfrechen/Qualification-DDI-CYP3A4/blob/7641759048775649e0de7ede9f554184a80c0029/input/master_quali_plan.json#L2866

**Comment by sfrechen** [comment]
Fixed.
